import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import UserDropdown from "@/components/user-dropdown";
import { Toaster } from "@/components/ui/toaster";
import Nav from "@/components/nav";
import Footer from "@/components/footer";
import BackgroundVideo from "@/components/background-video";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Technorollix",
  description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[#1c0404]`}
      >
        <div className="max-w-screen-xl mx-auto ">
          
          <Nav />
          {children}
        </div>
          
          <Footer />
		  <Toaster />
      </body>
    </html>
  );
}
